include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

test:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
